// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYG1QRI5v69QR7CgvN7jrpbdhp0U3_IU',
    appId: '1:1013050577060:web:4a146adbe3a8ad85f71631',
    messagingSenderId: '1013050577060',
    projectId: 'meumovi',
    authDomain: 'meumovi.firebaseapp.com',
    storageBucket: 'meumovi.appspot.com',
    measurementId: 'G-85XFQY03D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpIYcSCEcE0kVhRU_WSMLOG93UC7oaTY',
    appId: '1:1013050577060:android:9d700e8e2498e6eaf71631',
    messagingSenderId: '1013050577060',
    projectId: 'meumovi',
    storageBucket: 'meumovi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuMXm2GaiWYUVKYXaCBdPzReOduA14Uk',
    appId: '1:1013050577060:ios:f13d24a5b1b95e69f71631',
    messagingSenderId: '1013050577060',
    projectId: 'meumovi',
    storageBucket: 'meumovi.appspot.com',
    iosBundleId: 'br.com.dcbsystem.meuMovi',
  );
}
